site_name: Triaxis Tech Docs
site_url: http://192.168.2.25:8005

theme:
  name: material
  font:
    text: Roboto

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
  #  - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
  #  - navigation.sections
  #  - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  #  - toc.integrate

  plugins:
    - typeset
    - search
    - blog
    - privacy:
        links_attr_map:
          target: _blank

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
